# Generated by Django 2.1.1 on 2018-09-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ewaste', '0002_auto_20180922_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=250)),
                ('joint', models.CharField(max_length=500)),
                ('time', models.DateField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Specific',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=250)),
                ('quantity', models.CharField(max_length=500)),
                ('time', models.DateField(max_length=100)),
            ],
        ),
    ]
