# Generated by Django 2.1.1 on 2018-09-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewaste', '0003_general_specific'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general',
            name='time',
            field=models.DateTimeField(max_length=100),
        ),
        migrations.AlterField(
            model_name='specific',
            name='time',
            field=models.DateTimeField(max_length=100),
        ),
    ]
