# Generated by Django 2.1.1 on 2018-09-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewaste', '0004_auto_20180924_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='specific',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
